version: "3.8"
services:
  user-svc:
    container_name: 'user-svc'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    volumes:
      - /app/node_modules
      - /app/dist
      - ./:/app




