version: "3.8"
services:
  user-svc:
    container_name: 'user-svc'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_CONNECTION_STRING=mongodb://root:example@wd-mongo:27017/auth-service?authSource=admin
      - REDIS_URL=redis://wd-redis:6379
      - USER_SERVICE_PORT=3005
    ports:
      - '3005:3005'
    volumes:
      - /app/node_modules
      - /app/dist
      - ./:/app




